// Package launcher exposes spawn's instance-provisioning logic as a headless,
// importable library so SDK consumers (lagotto's capacity-poller Lambda, cohort,
// future schedulers) get the SAME spored bootstrap and launch orchestration the
// `spawn launch` CLI uses — instead of calling the low-level aws.Client.Launch
// directly and ending up with "naked" instances that have no spored, never run
// their command, and ignore on-complete/pre-stop (lagotto#19).
//
// The two entry points:
//
//   - BuildLinuxBootstrap builds the spored bootstrap user-data as a pure
//     function of (username, public key, plugins). All runtime behavior
//     (command, on-complete, pre-stop, idle-timeout, TTL) is driven by the
//     spawn:* EC2 tags that aws.buildTags writes from the LaunchConfig — the
//     script reads them at boot — so this function needs no disk, no
//     platform.Detect, and no CLI globals.
//   - Provision performs the headless launch minimum: auto-detect AMI when
//     empty, set up the spored IAM instance profile when empty, build the
//     bootstrap user-data, then Launch. SSM-only is fine (the spored role
//     attaches AmazonSSMManagedInstanceCore), so no on-disk SSH key is required.
package launcher

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"

	"github.com/spore-host/spawn/pkg/plugin"
	"github.com/spore-host/spawn/pkg/security"
)

// EncodeLinuxUserData encodes a bootstrap script for EC2 RunInstances. EC2
// requires the UserData field to be base64; cloud-init (AL2023/Ubuntu) also
// transparently gunzips it, so we gzip+base64 to match what the `spawn launch`
// CLI sends. Callers that build a script with BuildLinuxBootstrap MUST pass it
// through here before assigning aws.LaunchConfig.UserData — RunInstances rejects
// raw text with "Invalid BASE64 encoding of user data" (#127).
func EncodeLinuxUserData(script string) string {
	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	_, _ = gz.Write([]byte(script))
	_ = gz.Close()
	return base64.StdEncoding.EncodeToString(buf.Bytes())
}

// BootstrapConfig parameterizes the Linux spored bootstrap. These are the ONLY
// values baked into the script text; everything else is read from spawn:* tags
// at instance boot.
type BootstrapConfig struct {
	// Username is the local Linux user the instance creates (e.g. "ec2-user").
	Username string
	// PublicKey is the SSH public key (authorized_keys line, raw bytes) the
	// instance trusts. May be empty for an SSM-only instance with no SSH key —
	// the bootstrap then writes an empty authorized_keys (harmless), and a key
	// can be injected later over SSM by `spawn connect`.
	PublicKey []byte
	// Plugins are spored plugin declarations written to /etc/spawn/plugins.json.
	Plugins []plugin.Declaration
	// CustomUserData, if non-empty, is appended verbatim after the bootstrap so
	// the user's own script runs once spored is installed. Equivalent to the
	// CLI's --user-data (already-resolved text, no @file indirection here —
	// headless callers pass the content directly).
	CustomUserData string
	// StorageScript, if non-empty, mounts attached storage (EFS/FSx/EBS data
	// volumes). It runs BEFORE CustomUserData so the user's workload sees the
	// mounts already live — mounting after the workload finishes is useless
	// (#166). Generated by pkg/userdata.GenerateStorageUserData.
	StorageScript string
	// Command, if non-empty, is the --command workload, embedded directly in the
	// bootstrap (written to /etc/spawn/command) instead of the spawn:command EC2
	// tag (#214/#246). EC2 tag values cap at 256 chars, so a non-trivial command
	// can't ride the tag; user-data (~16KB) carries it instead. The bootstrap
	// prefers this embedded file over the tag, so the tag stays free for the
	// parameter-sweep path's short per-instance commands.
	Command string
}

// BuildLinuxBootstrap returns the cloud-init user-data script that installs
// spored and configures the instance. It is the single source of truth for the
// Linux bootstrap, shared by the `spawn launch` CLI and headless SDK callers.
func BuildLinuxBootstrap(cfg BootstrapConfig) (string, error) {
	username := cfg.Username
	if username == "" {
		return "", fmt.Errorf("bootstrap: username is required")
	}
	publicKeyBase64 := base64.StdEncoding.EncodeToString(cfg.PublicKey)

	if err := security.ValidateUsername(username); err != nil {
		return "", fmt.Errorf("invalid username: %w", err)
	}
	// An empty key is valid: it produces an empty authorized_keys, i.e. an
	// SSM-only / keyless instance (lagotto's Lambda has no SSH key on disk). Only
	// validate the encoding when a key was actually supplied.
	if len(cfg.PublicKey) > 0 {
		if err := security.ValidateBase64(publicKeyBase64); err != nil {
			return "", fmt.Errorf("invalid public key encoding: %w", err)
		}
	}

	script := fmt.Sprintf(`#!/bin/bash
set -e

# User configuration
LOCAL_USERNAME=%s
LOCAL_SSH_KEY_BASE64=%s
`, security.ShellEscape(username), security.ShellEscape(publicKeyBase64))

	// Embed the --command workload directly in user-data (#214/#246) instead of
	// the 256-char-capped spawn:command tag. Written BEFORE linuxBootstrapBody so
	// the file exists when the body's command-exec block reads it. A single-quoted
	// here-doc delimiter keeps the command verbatim (no shell expansion at write
	// time); EOFSPAWNCMD is unlikely to collide with real command text.
	if cfg.Command != "" {
		script += fmt.Sprintf(`
# Embedded --command workload (user-data, not the spawn:command tag; #214/#246)
mkdir -p /etc/spawn
cat > /etc/spawn/command <<'EOFSPAWNCMD'
%s
EOFSPAWNCMD
chmod 600 /etc/spawn/command
`, cfg.Command)
	}

	script += linuxBootstrapBody

	// Inject plugin declarations for spored to load at startup.
	if len(cfg.Plugins) > 0 {
		declJSON, err := json.Marshal(cfg.Plugins)
		if err != nil {
			return "", fmt.Errorf("marshal plugin declarations: %w", err)
		}
		script += fmt.Sprintf(`
# Write plugin declarations for spored to load at startup
mkdir -p /etc/spawn
cat > /etc/spawn/plugins.json <<'EOFPLUGINS'
%s
EOFPLUGINS
chmod 644 /etc/spawn/plugins.json
echo "Plugin declarations written: %d plugin(s)"
`, string(declJSON), len(cfg.Plugins))
	}

	// Mount attached storage BEFORE the user's script, so the workload sees the
	// volumes already live (#166). The storage script does its own mkdir + mount;
	// keep `set -e` paused around it so a mount hiccup can't abort the whole
	// user-data before the user's script even runs.
	if cfg.StorageScript != "" {
		script += "\n# Attached storage (mounted before the user script so the workload sees it; #166)\nset +e\n"
		script += cfg.StorageScript
	}

	if cfg.CustomUserData != "" {
		// Run the user's script in its own section. The bootstrap above uses
		// `set -e`, so without resetting it a non-fatal earlier failure would
		// skip the user's script entirely and cloud-init would mark the whole
		// user-data failed (#27). Disable -e here so the user's script runs and
		// reports its own exit status; if the user wants strict mode they can
		// re-enable `set -e` at the top of their script.
		script += "\n# Custom user data (runs regardless of bootstrap warnings)\nset +e\n"
		script += cfg.CustomUserData
	}

	return script, nil
}

// linuxBootstrapBody is the static, tag-driven remainder of the bootstrap. It
// reads all behavior (session-timeout, job-array/sweep env, spawn:command,
// on-complete, etc.) from spawn:* EC2 tags at boot, so it is independent of any
// LaunchConfig value beyond the username/key spliced in above.
const linuxBootstrapBody = `

# Detect architecture
ARCH=$(uname -m)
echo "Installing spored for architecture: $ARCH"

# Detect region
TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" 2>/dev/null || true)
if [ -n "$TOKEN" ]; then
    REGION=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/placement/region 2>/dev/null)
else
    REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region 2>/dev/null || echo "us-east-1")
fi

echo "Region: $REGION"

# Determine binary name
case "$ARCH" in
    x86_64)
        BINARY="spored-linux-amd64"
        ;;
    aarch64)
        BINARY="spored-linux-arm64"
        ;;
    *)
        echo "Unsupported architecture: $ARCH"
        exit 1
        ;;
esac

# Download from S3 (public buckets, regional for low latency)
S3_BASE_URL="https://spawn-binaries-${REGION}.s3.amazonaws.com"
FALLBACK_URL="https://spawn-binaries-us-east-1.s3.amazonaws.com"
PROJECT="spawn"

echo "Downloading spored binary..."

# Download to a temp path, NOT directly over /usr/local/bin/spored. Writing in
# place fails with "Text file busy" (ETXTBSY) if a spored is already running
# (baked into the AMI or from a previous boot); we install via atomic rename
# below, which the kernel allows even while the old binary executes (#27).
SPORED_TMP="$(mktemp /tmp/spored.XXXXXX)"

# Try regional bucket with project prefix first, then without prefix (legacy), then fallback to us-east-1
if curl -f -o "$SPORED_TMP" "${S3_BASE_URL}/${PROJECT}/${BINARY}" 2>/dev/null; then
    CHECKSUM_URL="${S3_BASE_URL}/${PROJECT}/${BINARY}.sha256"
    echo "Downloaded from ${REGION}"
elif curl -f -o "$SPORED_TMP" "${S3_BASE_URL}/${BINARY}" 2>/dev/null; then
    CHECKSUM_URL="${S3_BASE_URL}/${BINARY}.sha256"
    echo "Downloaded from ${REGION} (legacy path)"
else
    echo "Regional bucket unavailable, trying us-east-1..."
    if curl -f -o "$SPORED_TMP" "${FALLBACK_URL}/${PROJECT}/${BINARY}" 2>/dev/null; then
        CHECKSUM_URL="${FALLBACK_URL}/${PROJECT}/${BINARY}.sha256"
    else
        curl -f -o "$SPORED_TMP" "${FALLBACK_URL}/${BINARY}" || {
            echo "Failed to download spored binary"
            rm -f "$SPORED_TMP"
            exit 1
        }
        CHECKSUM_URL="${FALLBACK_URL}/${BINARY}.sha256"
    fi
    echo "Downloaded from us-east-1"
fi

# Download and verify SHA256 checksum (against the temp file).
echo "Verifying checksum..."
curl -f -o /tmp/spored.sha256 "${CHECKSUM_URL}" || {
    echo "Failed to download checksum"
    rm -f "$SPORED_TMP"
    exit 1
}

EXPECTED_CHECKSUM=$(cat /tmp/spored.sha256)
ACTUAL_CHECKSUM=$(sha256sum "$SPORED_TMP" | awk '{print $1}')

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
    echo "❌ Checksum verification failed!"
    echo "   Expected: $EXPECTED_CHECKSUM"
    echo "   Actual:   $ACTUAL_CHECKSUM"
    rm -f "$SPORED_TMP"
    exit 1
fi

echo "✅ Checksum verified: $EXPECTED_CHECKSUM"
chmod +x "$SPORED_TMP"

# Stop any running spored so the rename doesn't leave a stale daemon, then
# atomically move the verified binary into place. rename(2) over a busy binary
# is permitted — the running process keeps the old (now-unlinked) inode — so
# this never hits ETXTBSY.
systemctl stop spored 2>/dev/null || true
mv -f "$SPORED_TMP" /usr/local/bin/spored

# Setup local user account
echo "Setting up user: $LOCAL_USERNAME"

# Create user if doesn't exist
if ! id "$LOCAL_USERNAME" &>/dev/null; then
    useradd -m -s /bin/bash "$LOCAL_USERNAME"
    echo "Created user: $LOCAL_USERNAME"
fi

# Add to sudo/wheel group (passwordless sudo like ec2-user)
usermod -aG wheel "$LOCAL_USERNAME" 2>/dev/null || usermod -aG sudo "$LOCAL_USERNAME" 2>/dev/null
echo "$LOCAL_USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$LOCAL_USERNAME
chmod 0440 /etc/sudoers.d/$LOCAL_USERNAME

# Setup SSH for local user
mkdir -p /home/$LOCAL_USERNAME/.ssh
chmod 700 /home/$LOCAL_USERNAME/.ssh

# Decode and write SSH public key
echo "$LOCAL_SSH_KEY_BASE64" | base64 -d > /home/$LOCAL_USERNAME/.ssh/authorized_keys
chmod 600 /home/$LOCAL_USERNAME/.ssh/authorized_keys
chown -R $LOCAL_USERNAME:$LOCAL_USERNAME /home/$LOCAL_USERNAME/.ssh

echo "✅ User $LOCAL_USERNAME configured with SSH access and sudo privileges"

# Configure automatic logout for idle sessions
# This prevents indefinite logins when users leave sessions idle
echo "Configuring session timeouts..."

# Get session timeout from EC2 tags
INSTANCE_ID=$(ec2-metadata --instance-id | cut -d " " -f 2)
SESSION_TIMEOUT=$(aws ec2 describe-tags --region $REGION \
    --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:session-timeout" \
    --query 'Tags[0].Value' --output text 2>/dev/null || echo "30m")

# Convert duration to seconds
parse_duration() {
    local duration="$1"
    local total=0

    # Handle 0 or disabled
    if [ "$duration" = "0" ] || [ "$duration" = "disabled" ]; then
        echo "0"
        return
    fi

    # Parse duration (e.g., 30m, 1h30m, 2h)
    while [[ $duration =~ ([0-9]+)([smhd]) ]]; do
        local value="${BASH_REMATCH[1]}"
        local unit="${BASH_REMATCH[2]}"

        case "$unit" in
            s) total=$((total + value)) ;;
            m) total=$((total + value * 60)) ;;
            h) total=$((total + value * 3600)) ;;
            d) total=$((total + value * 86400)) ;;
        esac

        duration="${duration#*${BASH_REMATCH[0]}}"
    done

    echo "$total"
}

TIMEOUT_SECONDS=$(parse_duration "$SESSION_TIMEOUT")

if [ "$TIMEOUT_SECONDS" -gt 0 ]; then
    # SSH server timeout (disconnect idle SSH connections)
    # Use 1/2 of session timeout for SSH keepalive
    SSH_INTERVAL=$((TIMEOUT_SECONDS / 6))
    if [ $SSH_INTERVAL -lt 60 ]; then
        SSH_INTERVAL=60
    fi

    if ! grep -q "^ClientAliveInterval" /etc/ssh/sshd_config; then
        echo "ClientAliveInterval $SSH_INTERVAL" >> /etc/ssh/sshd_config
        echo "ClientAliveCountMax 3" >> /etc/ssh/sshd_config
        systemctl reload sshd 2>/dev/null || service sshd reload 2>/dev/null || true
    fi

    # Shell timeout (auto-logout idle shells)
    # Set TMOUT for all users via /etc/profile.d/
    cat > /etc/profile.d/session-timeout.sh <<EOFTIMEOUT
# Automatic logout for idle shells ($SESSION_TIMEOUT)
# Prevents indefinite logins when users leave sessions idle
# Note: readonly prevents users from unsetting it
export TMOUT=$TIMEOUT_SECONDS
readonly TMOUT
EOFTIMEOUT

    chmod 644 /etc/profile.d/session-timeout.sh

    echo "✅ Session timeouts configured (Timeout: $SESSION_TIMEOUT)"
else
    echo "✅ Session timeouts disabled (set spawn:session-timeout tag to enable)"
fi

# Setup job array environment variables (if part of a job array)
JOB_ARRAY_ID=$(aws ec2 describe-tags --region $REGION \
    --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:job-array-id" \
    --query 'Tags[0].Value' --output text 2>/dev/null || echo "None")

if [ "$JOB_ARRAY_ID" != "None" ]; then
    echo "Setting up job array environment..."

    JOB_ARRAY_NAME=$(aws ec2 describe-tags --region $REGION \
        --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:job-array-name" \
        --query 'Tags[0].Value' --output text 2>/dev/null || echo "")

    JOB_ARRAY_SIZE=$(aws ec2 describe-tags --region $REGION \
        --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:job-array-size" \
        --query 'Tags[0].Value' --output text 2>/dev/null || echo "0")

    JOB_ARRAY_INDEX=$(aws ec2 describe-tags --region $REGION \
        --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:job-array-index" \
        --query 'Tags[0].Value' --output text 2>/dev/null || echo "0")

    # Create job array environment file
    cat > /etc/profile.d/job-array.sh <<EOFJOBARRAY
# Job Array Environment Variables
# Available to all shells for coordinated distributed computing
export JOB_ARRAY_ID="$JOB_ARRAY_ID"
export JOB_ARRAY_NAME="$JOB_ARRAY_NAME"
export JOB_ARRAY_SIZE="$JOB_ARRAY_SIZE"
export JOB_ARRAY_INDEX="$JOB_ARRAY_INDEX"
EOFJOBARRAY

    chmod 644 /etc/profile.d/job-array.sh

    echo "✅ Job array environment configured (Index: $JOB_ARRAY_INDEX/$JOB_ARRAY_SIZE)"
fi

# Setup parameter sweep environment variables (if part of a sweep)
SWEEP_ID=$(aws ec2 describe-tags --region $REGION \
    --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:sweep-id" \
    --query 'Tags[0].Value' --output text 2>/dev/null || echo "None")

if [ "$SWEEP_ID" != "None" ]; then
    echo "Setting up parameter sweep environment..."

    SWEEP_NAME=$(aws ec2 describe-tags --region $REGION \
        --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:sweep-name" \
        --query 'Tags[0].Value' --output text 2>/dev/null || echo "")

    SWEEP_SIZE=$(aws ec2 describe-tags --region $REGION \
        --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:sweep-size" \
        --query 'Tags[0].Value' --output text 2>/dev/null || echo "0")

    SWEEP_INDEX=$(aws ec2 describe-tags --region $REGION \
        --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:sweep-index" \
        --query 'Tags[0].Value' --output text 2>/dev/null || echo "0")

    # Query all spawn:param:* tags
    PARAM_TAGS=$(aws ec2 describe-tags --region $REGION \
        --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:param:*" \
        --query 'Tags[*].[Key,Value]' --output text 2>/dev/null || echo "")

    # Create parameter sweep environment file
    cat > /etc/profile.d/spawn-params.sh <<EOFPARAMS
# Parameter Sweep Environment Variables
# Available to all shells for parameter sweep workloads
export SWEEP_ID="$SWEEP_ID"
export SWEEP_NAME="$SWEEP_NAME"
export SWEEP_SIZE="$SWEEP_SIZE"
export SWEEP_INDEX="$SWEEP_INDEX"

# Parse and export PARAM_* environment variables from tags
EOFPARAMS

    # Parse param tags and add exports
    echo "$PARAM_TAGS" | while IFS=$'\t' read -r key value; do
        if [[ $key == spawn:param:* ]]; then
            param_name=${key#spawn:param:}
            echo "export PARAM_${param_name}=\"${value}\"" >> /etc/profile.d/spawn-params.sh
        fi
    done

    chmod 644 /etc/profile.d/spawn-params.sh

    echo "✅ Parameter sweep environment configured (Index: $SWEEP_INDEX/$SWEEP_SIZE)"
fi

# Execute the --command workload if specified. This runs for ANY instance
# carrying a spawn:command tag, not just parameter-sweep instances. Previously
# this block was nested inside the SWEEP_ID gate above, so a plain single
# launch with --command silently never ran the command (#61).
#
# Source order (#214/#246): an embedded command baked into this user-data takes
# precedence over the spawn:command tag. EC2 tag values are capped at 256 chars,
# so a non-trivial --command can't be delivered via the tag; spawn now embeds the
# plain --command here (user-data is ~16KB) and reserves the tag for the
# parameter-sweep path, which sets a short per-instance command. If the embedded
# file is absent (sweeps, older callers), fall back to the tag as before.
if [ -s /etc/spawn/command ]; then
    WORKFLOW_COMMAND="(embedded)"
    STEP_NAME=""
else
    WORKFLOW_COMMAND=$(aws ec2 describe-tags --region $REGION \
        --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:command" \
        --query 'Tags[0].Value' --output text 2>/dev/null || echo "None")
    STEP_NAME=$(aws ec2 describe-tags --region $REGION \
        --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:step" \
        --query 'Tags[0].Value' --output text 2>/dev/null || echo "")
fi

if [ "$WORKFLOW_COMMAND" != "None" ] && [ -n "$WORKFLOW_COMMAND" ]; then
    if [ -n "$STEP_NAME" ]; then
        echo "▶️  Executing workflow step: $STEP_NAME"
    else
        echo "▶️  Executing --command"
    fi

    # Create command execution script. Source the parameter-sweep env first if
    # present (sweep instances), but don't require it (single instances).
    cat > /tmp/spawn-command.sh <<'EOFCMD'
#!/bin/bash
set -e
[ -f /etc/profile.d/spawn-params.sh ] && source /etc/profile.d/spawn-params.sh
EOFCMD
    # Embedded command (baked into user-data, #214/#246) wins; else the tag value.
    if [ -s /etc/spawn/command ]; then
        cat /etc/spawn/command >> /tmp/spawn-command.sh
    else
        echo "$WORKFLOW_COMMAND" >> /tmp/spawn-command.sh
    fi
    chmod +x /tmp/spawn-command.sh

    # Execute command as the instance's primary user in the background.
    # ($LOCAL_USERNAME is the user the bootstrap creates above; the previous
    # hardcoded "local" user never exists, so the command silently failed — #61.)
    # Log output to both file and console.
    su - "$LOCAL_USERNAME" -c '/tmp/spawn-command.sh' 2>&1 | tee /var/log/spawn-command.log &

    echo "✅ Command execution started (logs: /var/log/spawn-command.log)"
fi

# Create login banner (MOTD) with spore configuration
echo "Creating login banner..."

# Get all spore tags for the banner
TTL_TAG=$(aws ec2 describe-tags --region $REGION \
    --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:ttl" \
    --query 'Tags[0].Value' --output text 2>/dev/null || echo "disabled")

IDLE_TIMEOUT_TAG=$(aws ec2 describe-tags --region $REGION \
    --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:idle-timeout" \
    --query 'Tags[0].Value' --output text 2>/dev/null || echo "disabled")

ON_COMPLETE_TAG=$(aws ec2 describe-tags --region $REGION \
    --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=spawn:on-complete" \
    --query 'Tags[0].Value' --output text 2>/dev/null || echo "disabled")

# Create the banner with optional job array info
if [ "$JOB_ARRAY_ID" != "None" ]; then
cat > /etc/motd <<EOFMOTD
╔═══════════════════════════════════════════════════════════════╗
║                  🌱 Welcome to Spore                         ║
╚═══════════════════════════════════════════════════════════════╝

Instance: $INSTANCE_ID
Region:   $REGION

Job Array:
  • Array Name:       $JOB_ARRAY_NAME
  • Array ID:         $JOB_ARRAY_ID
  • Instance Index:   $JOB_ARRAY_INDEX / $JOB_ARRAY_SIZE

Spore Agent Configuration:
  • TTL:              $TTL_TAG
  • Idle Timeout:     $IDLE_TIMEOUT_TAG
  • On Complete:      $ON_COMPLETE_TAG
  • Session Timeout:  $SESSION_TIMEOUT

⚠️  IMPORTANT: This shell will auto-logout after $SESSION_TIMEOUT of inactivity
⚠️  SSH connections will disconnect if idle for extended periods

To view current status:
  sudo spored status

To extend TTL:
  spawn extend <instance-id> <new-ttl>

Documentation: https://github.com/spore-host/spore-host

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOFMOTD
else
cat > /etc/motd <<EOFMOTD
╔═══════════════════════════════════════════════════════════════╗
║                  🌱 Welcome to Spore                         ║
╚═══════════════════════════════════════════════════════════════╝

Instance: $INSTANCE_ID
Region:   $REGION

Spore Agent Configuration:
  • TTL:              $TTL_TAG
  • Idle Timeout:     $IDLE_TIMEOUT_TAG
  • On Complete:      $ON_COMPLETE_TAG
  • Session Timeout:  $SESSION_TIMEOUT

⚠️  IMPORTANT: This shell will auto-logout after $SESSION_TIMEOUT of inactivity
⚠️  SSH connections will disconnect if idle for extended periods

To view current status:
  sudo spored status

To extend TTL:
  spawn extend <instance-id> <new-ttl>

Documentation: https://github.com/spore-host/spore-host

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOFMOTD
fi

chmod 644 /etc/motd
echo "✅ Login banner created"

# Install acpid so AWS stop/terminate signals trigger a graceful shutdown
# rather than a hard kill after the ACPI timeout.
dnf install -y acpid 2>/dev/null || yum install -y acpid 2>/dev/null || true
systemctl enable --now acpid

# Create systemd service
cat > /etc/systemd/system/spored.service <<'EOFSERVICE'
[Unit]
Description=Spawn Agent - Instance self-monitoring
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
# SigV4-sign DNS registration requests (#173). Harmless today (the DNS Function
# URL is still AuthType: NONE, which ignores the signature), this fields a
# signing fleet ahead of the AuthType: AWS_IAM flip so the cutover doesn't break
# registration for in-flight instances. Old non-signing instances age out under
# their TTLs ("everything dies"), so by the time the flip lands the fleet signs.
Environment=SPORE_DNS_SIGV4=1
ExecStart=/usr/local/bin/spored
# on-failure (not always) prevents restart attempts during graceful shutdown
Restart=on-failure
RestartSec=10
# Give spored time to deregister DNS and clean up before SIGKILL
TimeoutStopSec=30
StandardOutput=journal
StandardError=journal
NoNewPrivileges=true
# Do NOT set PrivateTmp=true: spored must see the host /tmp/SPAWN_COMPLETE
# completion file written by users / spawn connect / nf-spawn. PrivateTmp
# isolates the daemon's /tmp and silently breaks --on-complete/--pre-stop (#66).

[Install]
WantedBy=multi-user.target
EOFSERVICE

# Enable and start
systemctl daemon-reload
systemctl enable spored
systemctl start spored

echo "spored installation complete"
`
