package launcher

import (
	"context"
	"fmt"

	"github.com/spore-host/spawn/pkg/aws"
	"github.com/spore-host/spawn/pkg/launchererr"
	"github.com/spore-host/spawn/pkg/plugin"
)

// ErrPostLaunch marks a failure that happened AFTER RunInstances already
// succeeded (e.g. ephemeral FSx setup). The instance was launched and has since
// been torn down by Provision (#220). Callers that retry across AZs/regions
// should treat a post-launch failure as terminal: the launch itself worked, so
// retrying won't help and would just churn launch+terminate cycles. Test with
// errors.Is(err, ErrPostLaunch).
//
// The sentinel now lives in the dependency-free leaf [launchererr] so a
// downstream can match it without importing the launcher's AWS SDK tree
// (spawn#354); this alias keeps every existing caller and errors.Is call working.
var ErrPostLaunch = launchererr.ErrPostLaunch

// DefaultUsername is the local user created on instances provisioned headlessly
// (no $USER to read). It matches the Amazon Linux default that `spawn connect`
// assumes, so connect works without --user.
const DefaultUsername = "ec2-user"

// Options tune a headless Provision. The zero value is valid: Linux,
// ec2-user, SSM-only (no SSH key), no plugins.
type Options struct {
	// Username overrides the local user the bootstrap creates. Empty =>
	// DefaultUsername.
	Username string
	// PublicKey is the SSH public key (authorized_keys line) to trust. Empty =>
	// SSM-only instance with no SSH key; `spawn connect` can inject one later
	// over SSM (lagotto#19 — the capacity-poller Lambda has no key on disk).
	PublicKey []byte
	// Plugins are spored plugin declarations to bake into the instance.
	Plugins []plugin.Declaration
	// CustomUserData is appended verbatim after the bootstrap (already-resolved
	// text; headless callers have no @file indirection).
	CustomUserData string
	// StorageScript, if non-empty, mounts attached storage (EFS/FSx/EBS data
	// volumes) before the workload command runs (#166). Generated by
	// pkg/userdata.GenerateStorageUserData; the CLI path builds the equivalent in
	// launch_single.go. Empty => no extra mounts (today's behavior).
	StorageScript string
}

// Provision performs the headless equivalent of `spawn launch`: it fills in the
// pieces the CLI normally resolves before calling aws.Client.Launch, so SDK
// consumers get a fully-functional spore (spored installed, command executed,
// on-complete/pre-stop/idle/TTL enforced) instead of a naked instance.
//
// Steps, each skipped when the caller already supplied the value:
//  1. AMI: if config.AMI is empty, auto-detect the recommended AL2023 AMI for
//     the region + instance type (arch and GPU are derived from the type).
//  2. IAM: if config.IamInstanceProfile is empty, set up the shared spored
//     instance profile (also attaches AmazonSSMManagedInstanceCore, so an
//     SSM-only / keyless instance is still reachable).
//  3. User-data: if config.UserData is empty, build the spored Linux bootstrap.
//     A caller that pre-set UserData (e.g. a fully custom script) is left alone.
//  4. Launch.
//
// Windows is out of scope here (no spored-on-Windows headless path yet, #77);
// callers must build Windows user-data themselves.
func Provision(ctx context.Context, client *aws.Client, config aws.LaunchConfig, opts Options) (*aws.LaunchResult, error) {
	if config.InstanceType == "" {
		return nil, fmt.Errorf("provision: instance type is required")
	}
	if config.Region == "" {
		return nil, fmt.Errorf("provision: region is required")
	}
	if config.TargetOS == "windows" {
		return nil, fmt.Errorf("provision: Windows is not supported by the headless launcher (build Windows user-data via the CLI)")
	}

	// 1. AMI auto-detection (lagotto#19 issue #1). GetRecommendedAMI derives the
	// CPU architecture and GPU-ness from the instance type, so a g5/arm64 type
	// gets the right AMI without the caller specifying anything.
	if config.AMI == "" {
		ami, err := client.GetRecommendedAMI(ctx, config.Region, config.InstanceType)
		if err != nil {
			return nil, fmt.Errorf("provision: auto-detect AMI for %s in %s: %w", config.InstanceType, config.Region, err)
		}
		config.AMI = ami
	}

	// 2. spored IAM instance profile. Without it spored can't read its tags or
	// self-terminate, and SSM connect can't fall back. The CLI's default path
	// uses exactly this profile.
	if config.IamInstanceProfile == "" {
		profile, err := client.SetupSporedIAMRole(ctx)
		if err != nil {
			return nil, fmt.Errorf("provision: set up spored IAM role: %w", err)
		}
		config.IamInstanceProfile = profile
	}

	// 3. spored bootstrap user-data (lagotto#19 issues #2/#3 root cause). This is
	// the script that installs spored and makes the spawn:command / on-complete /
	// pre-stop / idle tags actually do something.
	if config.UserData == "" {
		username := opts.Username
		if username == "" {
			username = DefaultUsername
		}
		bootstrap, err := BuildLinuxBootstrap(BootstrapConfig{
			Username:       username,
			PublicKey:      opts.PublicKey,
			Plugins:        opts.Plugins,
			StorageScript:  opts.StorageScript,
			CustomUserData: opts.CustomUserData,
			// Embed the workload command in user-data, not the 256-char-capped
			// spawn:command tag (#214/#246). The headless path is never a sweep.
			Command: config.JobArrayCommand,
		})
		if err != nil {
			return nil, fmt.Errorf("provision: build bootstrap: %w", err)
		}
		// RunInstances requires base64 user-data (cloud-init also gunzips it).
		// Encode here — assigning the raw script makes RunInstances fail with
		// "Invalid BASE64 encoding of user data" (#127).
		config.UserData = EncodeLinuxUserData(bootstrap)
		// Tag the primary user so spored runs the pre-stop hook as them, not root (#63).
		if config.Username == "" {
			config.Username = username
		}
	}

	// 3.5. Ephemeral FSx — validate the request BEFORE launching (#213). The FSx
	// itself is created AFTER RunInstances succeeds (step 5), so a capacity-failed
	// launch never creates a filesystem at all — no orphan, no create/teardown
	// churn on every retry (#210). But validation (fail-closed lifecycle, #193)
	// runs up front so a bad config fails fast without launching an instance.
	if config.FSxLustreCreate {
		if err := validateEphemeralFSx(&config); err != nil {
			return nil, err
		}
	}

	// 4. Launch. If this fails (e.g. InsufficientInstanceCapacity — the case
	// lagotto retries on), we return immediately: no FSx was created, so there's
	// nothing to clean up.
	result, err := client.Launch(ctx, config)
	if err != nil {
		return nil, fmt.Errorf("provision: launch: %w", err)
	}

	// 5. Now that we have compute, create the ephemeral FSx and tag the instance
	// spawn:fsx-pending so spored waits → DRA → mounts it once AVAILABLE (#194).
	// Created here (not before launch) so capacity failures cost nothing (#213).
	//
	// CRITICAL (#220): if this post-launch step fails, the instance has ALREADY
	// launched. Returning (nil, err) here would abandon a running, billable
	// instance — and the caller (e.g. lagotto's per-AZ retry loop) would treat it
	// as a failed attempt and launch ANOTHER one, orphaning one instance (+ any
	// FSx created before the failure) per attempt. So tear the instance down on a
	// post-launch failure: a partial provision must leave NOTHING billable behind
	// (the #193 fail-closed contract extends past RunInstances).
	if config.FSxLustreCreate {
		if err := createAndAttachEphemeralFSx(ctx, client, &config, result.InstanceID); err != nil {
			if termErr := client.Terminate(ctx, config.Region, result.InstanceID); termErr != nil {
				// Couldn't even terminate — surface loudly, but still flag post-launch
				// so the caller doesn't retry into the same downstream failure.
				return nil, fmt.Errorf("%w: post-launch FSx setup failed (%v) AND could not terminate the now-orphaned instance %s — TERMINATE IT MANUALLY to avoid cost leak: %v", ErrPostLaunch, err, result.InstanceID, termErr)
			}
			return nil, fmt.Errorf("%w: FSx setup failed, terminated instance %s to avoid a leak: %v", ErrPostLaunch, result.InstanceID, err)
		}
	}
	return result, nil
}

// validateEphemeralFSx enforces the fail-closed lifecycle contract (#193) for an
// ephemeral FSx request BEFORE the instance launches, so a bad config fails fast
// without billing an instance. Only "ephemeral" is valid on the headless path —
// durable is a deliberate, blocking up-front action (`spawn fsx create`, #195),
// not something a capacity-poller should do inline. The actual filesystem is
// created later, only after RunInstances succeeds (#213).
func validateEphemeralFSx(config *aws.LaunchConfig) error {
	switch config.FSxLifecycle {
	case "ephemeral":
		// ok
	case "durable":
		return fmt.Errorf("provision: durable FSx is not supported on the headless path — pre-create it (spawn fsx create) and mount by id/name instead")
	case "":
		return fmt.Errorf("provision: FSx create requires fsx lifecycle 'ephemeral' (durable is not supported headlessly)")
	default:
		return fmt.Errorf("provision: invalid fsx lifecycle %q (must be 'ephemeral')", config.FSxLifecycle)
	}
	if config.FSxS3Bucket == "" {
		return fmt.Errorf("provision: FSx create requires an S3 bucket")
	}
	return nil
}

// createAndAttachEphemeralFSx creates the ephemeral FSx AFTER a successful launch
// (#213) and tags the now-running instance spawn:fsx-pending (+ mount point and
// S3 import/export paths) so spored waits → DRA → mounts it once AVAILABLE (#194).
//
// Creating it here — not before RunInstances — means a capacity-failed launch
// never creates a filesystem, eliminating both the orphan risk and the
// create/teardown churn the pre-launch ordering incurred on every retry (#210).
// The compensating teardown is kept ONLY as a backstop for the narrow window
// where the create succeeds but the follow-on tagging fails: in that case the
// instance won't carry the pending lease, so spored would never mount and the
// reaper's refcount would never see it — so we delete the just-created FSx rather
// than leak it. (The reaper ephemeral-orphan net, #210, is the outer backstop.)
//
// Tagging timing: RunInstances returns while the instance is still pending/booting
// (tens of seconds before spored starts), so the post-launch CreateTags lands well
// before spored reads its tags; spored's periodic config refresh covers any
// eventual-consistency lag.
func createAndAttachEphemeralFSx(ctx context.Context, client *aws.Client, config *aws.LaunchConfig, instanceID string) error {
	importPath := config.FSxImportPath
	if importPath == "" {
		importPath = fmt.Sprintf("s3://%s/", config.FSxS3Bucket)
	}
	exportPath := config.FSxExportPath
	if exportPath == "" {
		exportPath = fmt.Sprintf("s3://%s/", config.FSxS3Bucket)
	}
	mountPoint := config.FSxMountPoint
	if mountPoint == "" {
		mountPoint = "/fsx"
	}
	capacity := config.FSxStorageCapacity
	if capacity == 0 {
		capacity = 1200 // PERSISTENT_2 minimum
	}

	// Co-locate the FSx with the instance's AZ (#194/#208): FSx Lustre is
	// single-AZ and the mounting instance must share its AZ. Prefer an explicit
	// subnet; else resolve a pinned --az to a subnet so the FSx doesn't fall back
	// to subnets[0] (a different AZ → unmountable cross-AZ FSx, and on accounts
	// whose subnets[0] AZ lacks PERSISTENT_2, a spurious "not available in this
	// availability zone" for every AZ).
	subnetID := config.SubnetID
	if aws.NeedsAZSubnetResolution(subnetID, config.AvailabilityZone) {
		s, serr := client.GetSubnetForAZ(ctx, config.Region, config.AvailabilityZone)
		if serr != nil {
			return fmt.Errorf("provision: could not find a subnet in az %s to co-locate the ephemeral FSx: %w", config.AvailabilityZone, serr)
		}
		subnetID = s
	}

	fsID, err := client.CreateFSxLustreFilesystemAsync(ctx, aws.FSxConfig{
		StackName:                config.Name,
		Region:                   config.Region,
		StorageCapacity:          capacity,
		PerUnitStorageThroughput: 125, // PERSISTENT_2 minimum
		S3Bucket:                 config.FSxS3Bucket,
		ImportPath:               importPath,
		ExportPath:               exportPath,
		AutoCreateBucket:         true,
		SubnetID:                 subnetID,
		SecurityGroupIDs:         config.SecurityGroupIDs,
		Lifecycle:                "ephemeral",
	})
	if err != nil {
		return fmt.Errorf("provision: start ephemeral FSx create: %w", err)
	}

	// Ensure Lustre ports on each SG used by both FSx and the instance (#316).
	for _, sgID := range config.SecurityGroupIDs {
		if err := client.EnsureLustrePorts(ctx, config.Region, sgID); err != nil {
			// Non-fatal: best-effort (matches the CLI), the mount may still work.
			_ = err
		}
	}

	// Tag the running instance so spored picks up the pending FSx and mounts it.
	// If this fails, the FSx has no owner (spored will never see it, reaper
	// refcount never counts it) — so tear it down rather than leak it (#210 backstop).
	tags := map[string]string{
		"spawn:fsx-pending":     fsID,
		"spawn:fsx-mount-point": mountPoint,
	}
	if importPath != "" {
		tags["spawn:fsx-s3-import-path"] = importPath
	}
	if exportPath != "" {
		tags["spawn:fsx-s3-export-path"] = exportPath
	}
	if err := client.UpdateInstanceTags(ctx, config.Region, instanceID, tags); err != nil {
		if delErr := client.DeleteFSxFilesystem(ctx, fsID, config.Region); delErr != nil {
			return fmt.Errorf("provision: tagged-instance FSx attach failed (%w) AND could not delete the now-orphaned FSx %s — DELETE IT MANUALLY to avoid quota/cost leak: %v", err, fsID, delErr)
		}
		return fmt.Errorf("provision: could not tag instance %s with pending FSx %s (deleted the FSx to avoid a leak): %w", instanceID, fsID, err)
	}

	config.FSxPending = fsID
	config.FSxImportPath = importPath
	config.FSxExportPath = exportPath
	config.FSxMountPoint = mountPoint
	return nil
}
