package taskproto

import (
	"fmt"
	"strings"
)

// flushScriptPath is where the bootstrap writes the terminal-flush hook and
// where spored looks for it.
//
// Deliberately under /etc/spawn (root-owned, created by cloud-init) and NOT
// /tmp: spored runs as root, and executing a script out of a world-writable
// directory would let any local user choose what root runs. The existing /tmp
// channel (/tmp/SPAWN_COMPLETE) is only ever READ as data, which is a different
// risk class from exec.
//
// A variable only so tests can point it at a temp file; it is not settable from
// the environment, for the reason above.
var flushScriptPath = "/etc/spawn/task-flush.sh"

// FlushScriptPath returns the absolute path of the terminal-flush hook.
func FlushScriptPath() string { return flushScriptPath }

// SetFlushScriptPathForTest overrides the hook path for the rest of this test
// binary's run and returns a function restoring the previous value.
func SetFlushScriptPathForTest(path string) (restore func()) {
	prev := flushScriptPath
	flushScriptPath = path
	return func() { flushScriptPath = prev }
}

// GenerateFlushScript builds the terminal-flush hook for one task (spawn#632).
//
// The problem it solves: a task killed by its own TTL left NOTHING. Both the
// command.log upload (wrapper.go, "best-effort copy of the command log") and the
// completion.json heredoc sit AFTER the user command, in sequence, so they only
// ever run if the command returns. When a lifecycle limit fires mid-command the
// log dies with the instance's disk — and that log is exactly what you need,
// because spawn_phase() has already written timestamped stage-in/pull/command
// markers by then. A reporter lost a 45-minute run and had no way to tell how far
// it got, so re-sizing the TTL was another blind guess. This is distinct from the
// two already-fixed neighbours #566 (a command that FAILS writes no record) and
// #561 (a lost output recorded as success): both of those assume the command
// returns. Here it neither succeeded nor failed — it was still running.
//
// Why a spored-invoked hook rather than a trap in the wrapper. A trap on
// SIGTERM/EXIT only fires during OS shutdown, which races an S3 upload against
// network teardown — the worst possible moment to need the network. spored's
// runPreStop already runs SYNCHRONOUSLY, with a timeout, BEFORE
// provider.Terminate/Stop/Hibernate, i.e. while the instance is still fully
// healthy. Hanging the flush there also means it covers every exit path spored
// mediates — TTL, cost limit, idle-stop, hibernate and spot interruption — not
// just the TTL case that was reported.
//
// Everything the hook needs is baked in at generate time. It must not depend on
// the wrapper's live shell state, because it runs as a different process (and as
// root, not the instance user) while the wrapper is still blocked on the user's
// command.
//
// The reason token arrives as $1 and is a stable machine token from
// pkg/agent (ttl_expired, cost_limit_exceeded, …), never the human log string:
// rewording a log message must not silently change a recorded retry class.
func GenerateFlushScript(spec *TaskSpec, resultsPrefix, region, runID string) string {
	var b strings.Builder
	p := func(format string, a ...interface{}) { fmt.Fprintf(&b, format, a...) }

	taskID := spec.TaskID
	// Resolved by the caller (EffectiveResultsPrefix), same as the wrapper.

	p("#!/bin/bash\n")
	p("# spawn task terminal-flush hook — task_id=%s (generated by 'spawn task run', spawn#632)\n", taskID)
	p("# Run by spored on every lifecycle exit path, BEFORE the instance goes away.\n")
	p("# $1 is the exit-reason token (see pkg/agent exitReason).\n")
	// Not `set -e`: every step here is best-effort salvage. Aborting on the first
	// failure would be the same mistake #566 fixed in the wrapper — a partial
	// record beats none, and the whole point of this script is that it runs when
	// something has already gone wrong.
	p("set +e -u -o pipefail\n")
	// spored is a systemd service, so this inherits a minimal PATH rather than the
	// login PATH the wrapper enjoys — the system directories are APPENDED to make
	// sure `aws` is reachable. Appended, not substituted: replacing PATH outright
	// would drop any aws CLI installed outside these six directories, which is not
	// hypothetical (Ubuntu's snap package puts it in /snap/bin). Losing the AWS CLI
	// is losing the whole point of this hook.
	p("export PATH=\"${PATH:-}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"\n\n")

	p("TASK_ID=%s\n", shQuote(taskID))
	p("RESULTS_PREFIX=%s\n", shQuote(resultsPrefix))
	p("AWS_REGION_ARG=%s\n", shQuote("--region="+region))
	p("REASON=\"${1:-unknown}\"\n\n")

	// The interlock. Without this the hook would overwrite the completion record
	// of every task that finished normally: the success path is command returns ->
	// wrapper writes completion.json -> wrapper signals SPAWN_COMPLETE -> spored
	// acts on on_complete -> terminate() -> runPreStop() -> this script. Relabelling
	// a completed task "failed/ttl_expired" would be a far worse bug than the one
	// being fixed, so the guard comes first and bails hardest.
	p("if [ -f %s ]; then\n", shQuote(CompletionRecordPath()))
	p("  echo \"spawn: task $TASK_ID already wrote its completion record; nothing to flush\"\n")
	p("  exit 0\n")
	p("fi\n\n")

	p("echo \"spawn: flushing a terminal record for task $TASK_ID (reason: $REASON)\"\n\n")

	// Reason -> retry class. Only the classes whose semantics actually match are
	// mapped; anything unrecognized gets an empty class ("unclassified terminal
	// state") rather than a guess, because Retryable() is read by adapters to
	// decide whether to spend money running the task again.
	p("case \"$REASON\" in\n")
	p("  %s) RETRY_CLASS=%s ;;\n", string(ExitTTLExpired), shQuote(string(RetryTTLExpired)))
	p("  %s) RETRY_CLASS=%s ;;\n", string(ExitSpotInterruption), shQuote(string(RetrySpotInterruption)))
	p("  *) RETRY_CLASS='' ;;\n")
	p("esac\n\n")

	// started_at comes from the file the wrapper persisted; an empty value is
	// honest about not knowing rather than inventing "now".
	p("STARTED_AT=\"$(cat %s 2>/dev/null)\"\n", shQuote(StartedAtPath()))
	p("ENDED_AT=\"$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)\"\n\n")

	// The log is the artifact that actually answers "how far did it get" — upload
	// it FIRST, before the record, so a hook that runs out of time still salvages
	// the more useful half.
	p("LOGS_JSON='[]'\n")
	p("if [ -f /var/log/spawn-command.log ]; then\n")
	p("  if aws \"$AWS_REGION_ARG\" s3 cp /var/log/spawn-command.log \"$RESULTS_PREFIX/command.log\"; then\n")
	p("    LOGS_JSON=\"[\\\"$RESULTS_PREFIX/command.log\\\"]\"\n")
	p("  else\n")
	p("    echo 'spawn: could not upload command.log' >&2\n")
	p("  fi\n")
	p("else\n")
	p("  echo 'spawn: no /var/log/spawn-command.log to upload' >&2\n")
	p("fi\n\n")

	// state is "failed", NOT a new "terminated" value. CompletionRecord.State is
	// documented `completed | failed` and six workflow adapters parse this exact
	// object; a third value would send every one of them down a default branch.
	// "failed" is also true — the task did not produce its outputs. The WHY, which
	// is what the reporter actually needed, rides in retry_class and
	// terminal_reason, both of which are additive and ignorable.
	//
	// exit_code is -1 to mean "the process never returned a status", which is the
	// honest distinction from a real 0 or a real non-zero exit.
	p("cat > %s <<JSON\n", shQuote(localPath(terminalFileName)))
	p("{\n")
	p("  \"task_id\": %s,\n", jsonStr(taskID))
	p("  \"run_id\": %s,\n", jsonStr(runID))
	p("  \"exit_code\": -1,\n")
	p("  \"state\": %s,\n", jsonStr(string(StateFailed)))
	p("  \"started_at\": \"$STARTED_AT\",\n")
	p("  \"ended_at\": \"$ENDED_AT\",\n")
	p("  \"logs\": $LOGS_JSON,\n")
	p("  \"retry_class\": \"$RETRY_CLASS\",\n")
	p("  \"terminal_reason\": \"$REASON\"\n")
	p("}\n")
	p("JSON\n")
	p("aws \"$AWS_REGION_ARG\" s3 cp %s \"$RESULTS_PREFIX/completion.json\" || true\n\n", shQuote(localPath(terminalFileName)))

	p("printf '%%s' '-1' > %s\n", shQuote(localPath(exitCodeFileName)))
	p("aws \"$AWS_REGION_ARG\" s3 cp %s \"$RESULTS_PREFIX/.exitcode\" || true\n\n", shQuote(localPath(exitCodeFileName)))

	p("echo \"spawn: terminal record written for task $TASK_ID\"\n")
	p("exit 0\n")

	return b.String()
}
