package taskproto

import (
	"fmt"
	"path"
	"sort"
	"strings"
)

// GenerateWrapper builds the self-contained bash script that runs one task on
// its ephemeral instance. It is assigned to aws.LaunchConfig.JobArrayCommand, so
// launcher.Provision embeds it as /etc/spawn/command → /tmp/spawn-command.sh.
// This wrapper IS the reference implementation of the task-execution protocol's
// on-instance contract: stage inputs, run the command, stage outputs, and write
// the durable completion record to S3 — regardless of whether the command
// succeeds.
//
// resultsBucket is the plain bucket name (no s3:// prefix); the record lands
// under tasks/<task_id>/ in it.
//
// Design notes (also commented in the emitted script):
//   - We do NOT `set -e`. Under -e the script would abort the instant the user
//     command exits non-zero, so stage-out and the completion record would never
//     run — defeating the purpose. We capture rc=$? explicitly and gate the rest.
//   - The user command is argv ([]string); each element is single-quoted and run
//     in a subshell so there is no shell re-parse of a joined string.
//   - Every interpolated value (command args, env values, paths, task_id) is
//     single-quoted via shQuote. Env keys are validated in TaskSpec.Validate.
func GenerateWrapper(spec *TaskSpec, resultsBucket string) string {
	var b strings.Builder
	p := func(format string, a ...interface{}) { fmt.Fprintf(&b, format, a...) }

	taskID := spec.TaskID
	resultsPrefix := fmt.Sprintf("s3://%s/tasks/%s", resultsBucket, taskID)

	p("#!/bin/bash\n")
	p("# spawn task wrapper — task_id=%s (generated by 'spawn task run', spawn#386)\n", taskID)
	p("# NOTE: intentionally not 'set -e' — we must survive a failing user command\n")
	p("# to still stage outputs and write the durable completion record.\n")
	p("set -u -o pipefail\n\n")

	p("TASK_ID=%s\n", shQuote(taskID))
	p("RESULTS_PREFIX=%s\n", shQuote(resultsPrefix))
	p("STARTED_AT=\"$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)\"\n\n")

	// ---- env ----
	if len(spec.Env) > 0 {
		p("# ---- task environment ----\n")
		for _, k := range sortedKeys(spec.Env) {
			p("export %s=%s\n", k, shQuote(spec.Env[k]))
		}
		p("\n")
	}

	// ---- stage-in ----
	p("# ---- stage-in ----\n")
	p("STAGE_RC=0\n")
	for _, m := range spec.Inputs {
		dir := path.Dir(m.Destination)
		if dir != "" && dir != "." && dir != "/" {
			p("mkdir -p %s\n", shQuote(dir))
		}
		p("if [ \"$STAGE_RC\" -eq 0 ]; then\n")
		p("  aws s3 cp%s %s %s || STAGE_RC=$?\n", recursiveFlag(m.Source), shQuote(m.Source), shQuote(m.Destination))
		p("fi\n")
	}
	p("\n")

	// ---- run user command ----
	p("# ---- run user command ----\n")
	p("rc=0\n")
	p("if [ \"$STAGE_RC\" -eq 0 ]; then\n")
	p("  ( %s )\n", quoteArgv(spec.Command))
	p("  rc=$?\n")
	p("else\n")
	p("  echo 'spawn: stage-in failed; skipping user command' >&2\n")
	p("  rc=$STAGE_RC\n")
	p("fi\n")
	p("ENDED_AT=\"$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)\"\n\n")

	// ---- stage-out (only when the command actually ran; runs even if it failed) ----
	p("# ---- stage-out (runs even when the user command failed) ----\n")
	p("OUT_RC=0\n")
	if len(spec.Outputs) > 0 {
		p("if [ \"$STAGE_RC\" -eq 0 ]; then\n")
		for _, m := range spec.Outputs {
			p("  aws s3 cp%s %s %s || OUT_RC=$?\n", recursiveFlag(m.Source), shQuote(m.Source), shQuote(m.Destination))
		}
		p("fi\n")
	}
	p("\n")

	// ---- classification + durable completion record ----
	p("# ---- classify + write the durable completion record ----\n")
	// state and retry_class are decided from STAGE_RC / rc.
	p("if [ \"$STAGE_RC\" -ne 0 ]; then\n")
	p("  STATE='failed'; RETRY_CLASS='%s'\n", RetryStagingError)
	p("elif [ \"$rc\" -ne 0 ]; then\n")
	p("  STATE='failed'; RETRY_CLASS='%s'\n", RetryAppError)
	p("else\n")
	p("  STATE='completed'; RETRY_CLASS=''\n")
	p("fi\n\n")

	// Best-effort copy of the command log; populates logs[] when it succeeds.
	p("LOGS_JSON='[]'\n")
	p("if aws s3 cp /var/log/spawn-command.log \"$RESULTS_PREFIX/command.log\"; then\n")
	p("  LOGS_JSON=\"[\\\"$RESULTS_PREFIX/command.log\\\"]\"\n")
	p("fi\n\n")

	// completion.json — the authoritative record. Built with a heredoc; all
	// interpolated values are either shell ints (rc) or our own controlled strings.
	p("cat > /tmp/spawn-completion.json <<JSON\n")
	p("{\n")
	p("  \"task_id\": %s,\n", jsonStr(taskID))
	p("  \"exit_code\": $rc,\n")
	p("  \"state\": \"$STATE\",\n")
	p("  \"started_at\": \"$STARTED_AT\",\n")
	p("  \"ended_at\": \"$ENDED_AT\",\n")
	p("  \"logs\": $LOGS_JSON,\n")
	p("  \"retry_class\": \"$RETRY_CLASS\"\n")
	p("}\n")
	p("JSON\n")
	p("aws s3 cp /tmp/spawn-completion.json \"$RESULTS_PREFIX/completion.json\" || true\n\n")

	// .exitcode — the plain-integer legacy signal the RFC names.
	p("printf '%%s' \"$rc\" > /tmp/spawn.exitcode\n")
	p("aws s3 cp /tmp/spawn.exitcode \"$RESULTS_PREFIX/.exitcode\" || true\n\n")

	// ---- signal spored ---- so on_complete fires and `spawn status --check-complete` works.
	p("# ---- signal spored (drives on_complete + spawn status --check-complete) ----\n")
	p("cat > /tmp/SPAWN_COMPLETE <<JSON\n")
	p("{\"status\": \"$STATE\", \"exit_code\": $rc, \"task_id\": %s}\n", jsonStr(taskID))
	p("JSON\n\n")

	p("exit $rc\n")

	return b.String()
}

// quoteArgv single-quotes each argv element and joins with spaces, so the result
// can be placed inside `( … )` and run as a command without a shell re-parse.
func quoteArgv(argv []string) string {
	parts := make([]string, len(argv))
	for i, a := range argv {
		parts[i] = shQuote(a)
	}
	return strings.Join(parts, " ")
}

// recursiveFlag returns " --recursive" when an S3/dir source is a prefix
// (trailing slash), matching `aws s3 cp` semantics for copying a whole prefix.
func recursiveFlag(source string) string {
	if strings.HasSuffix(source, "/") {
		return " --recursive"
	}
	return ""
}

// shQuote wraps s in single quotes, escaping embedded single quotes. This is the
// safe form for shell interpolation (unlike strconv.Quote, which uses
// double-quote semantics and would expand $ and backticks). Copied from the
// pattern in pkg/pluginruntime/remote_executor.go rather than reusing
// security.ShellEscape.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

// jsonStr renders a Go string as a JSON string literal (with surrounding quotes),
// used for the few values interpolated into the heredoc'd completion record.
func jsonStr(s string) string {
	// Escape the characters that matter inside a double-quoted JSON string.
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
