package taskproto

import (
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"
)

// GenerateWrapper builds the self-contained bash script that runs one task on
// its ephemeral instance. It is assigned to aws.LaunchConfig.JobArrayCommand, so
// launcher.Provision embeds it as /etc/spawn/command → /tmp/spawn-command.sh.
// This wrapper IS the reference implementation of the task-execution protocol's
// on-instance contract: stage inputs, run the command, stage outputs, and write
// the durable completion record to S3 — regardless of whether the command
// succeeds.
//
// resultsBucket is the plain bucket name (no s3:// prefix); the record lands
// under tasks/<task_id>/ in it. region is used only for the ECR login of a
// private-registry container image.
//
// Design notes (also commented in the emitted script):
//   - We do NOT `set -e`. Under -e the script would abort the instant the user
//     command exits non-zero, so stage-out and the completion record would never
//     run — defeating the purpose. We capture rc=$? explicitly and gate the rest.
//   - The user command is argv ([]string); each element is single-quoted and run
//     in a subshell (host) or as the container's argv so there is no shell
//     re-parse of a joined string.
//   - Every interpolated value (command args, env values, paths, task_id, image,
//     mount dirs) is single-quoted via shQuote. Env keys are validated in Validate.
//   - When spec.Container is set, the command runs inside that image via `docker
//     run` with the manifest dirs bind-mounted; stage-in/out still happen on the
//     host, so the image needs no aws CLI. Docker is installed on demand.
func GenerateWrapper(spec *TaskSpec, resultsBucket, region string) string {
	var b strings.Builder
	p := func(format string, a ...interface{}) { fmt.Fprintf(&b, format, a...) }

	taskID := spec.TaskID
	resultsPrefix := fmt.Sprintf("s3://%s/tasks/%s", resultsBucket, taskID)

	p("#!/bin/bash\n")
	p("# spawn task wrapper — task_id=%s (generated by 'spawn task run', spawn#386)\n", taskID)
	p("# NOTE: intentionally not 'set -e' — we must survive a failing user command\n")
	p("# to still stage outputs and write the durable completion record.\n")
	p("set -u -o pipefail\n\n")

	p("TASK_ID=%s\n", shQuote(taskID))
	p("RESULTS_PREFIX=%s\n", shQuote(resultsPrefix))
	p("STARTED_AT=\"$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)\"\n\n")

	// ---- env ----
	if len(spec.Env) > 0 {
		p("# ---- task environment ----\n")
		for _, k := range sortedKeys(spec.Env) {
			p("export %s=%s\n", k, shQuote(spec.Env[k]))
		}
		p("\n")
	}

	// ---- stage-in ----
	p("# ---- stage-in ----\n")
	p("STAGE_RC=0\n")
	for _, m := range spec.Inputs {
		dir := path.Dir(m.Destination)
		if dir != "" && dir != "." && dir != "/" {
			p("mkdir -p %s\n", shQuote(dir))
		}
		p("if [ \"$STAGE_RC\" -eq 0 ]; then\n")
		p("  aws s3 cp%s %s %s || STAGE_RC=$?\n", recursiveFlag(m.Source), shQuote(m.Source), shQuote(m.Destination))
		p("fi\n")
	}
	p("\n")

	// ---- run user command ----
	p("# ---- run user command ----\n")
	p("rc=0\n")
	p("if [ \"$STAGE_RC\" -eq 0 ]; then\n")
	if spec.Container != "" {
		writeContainerRun(p, spec, region)
	} else {
		// Host path: run argv in a subshell (no shell re-parse of a joined string).
		p("  ( %s )\n", quoteArgv(spec.Command))
		p("  rc=$?\n")
	}
	p("else\n")
	p("  echo 'spawn: stage-in failed; skipping user command' >&2\n")
	p("  rc=$STAGE_RC\n")
	p("fi\n")
	p("ENDED_AT=\"$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)\"\n\n")

	// ---- stage-out (only when the command actually ran; runs even if it failed) ----
	p("# ---- stage-out (runs even when the user command failed) ----\n")
	p("OUT_RC=0\n")
	if len(spec.Outputs) > 0 {
		p("if [ \"$STAGE_RC\" -eq 0 ]; then\n")
		for _, m := range spec.Outputs {
			p("  aws s3 cp%s %s %s || OUT_RC=$?\n", recursiveFlag(m.Source), shQuote(m.Source), shQuote(m.Destination))
		}
		p("fi\n")
	}
	p("\n")

	// ---- classification + durable completion record ----
	p("# ---- classify + write the durable completion record ----\n")
	// state and retry_class are decided from STAGE_RC / rc.
	p("if [ \"$STAGE_RC\" -ne 0 ]; then\n")
	p("  STATE='failed'; RETRY_CLASS='%s'\n", RetryStagingError)
	p("elif [ \"$rc\" -ne 0 ]; then\n")
	p("  STATE='failed'; RETRY_CLASS='%s'\n", RetryAppError)
	p("else\n")
	p("  STATE='completed'; RETRY_CLASS=''\n")
	p("fi\n\n")

	// Best-effort copy of the command log; populates logs[] when it succeeds.
	p("LOGS_JSON='[]'\n")
	p("if aws s3 cp /var/log/spawn-command.log \"$RESULTS_PREFIX/command.log\"; then\n")
	p("  LOGS_JSON=\"[\\\"$RESULTS_PREFIX/command.log\\\"]\"\n")
	p("fi\n\n")

	// completion.json — the authoritative record. Built with a heredoc; all
	// interpolated values are either shell ints (rc) or our own controlled strings.
	p("cat > /tmp/spawn-completion.json <<JSON\n")
	p("{\n")
	p("  \"task_id\": %s,\n", jsonStr(taskID))
	p("  \"exit_code\": $rc,\n")
	p("  \"state\": \"$STATE\",\n")
	p("  \"started_at\": \"$STARTED_AT\",\n")
	p("  \"ended_at\": \"$ENDED_AT\",\n")
	p("  \"logs\": $LOGS_JSON,\n")
	p("  \"retry_class\": \"$RETRY_CLASS\"\n")
	p("}\n")
	p("JSON\n")
	p("aws s3 cp /tmp/spawn-completion.json \"$RESULTS_PREFIX/completion.json\" || true\n\n")

	// .exitcode — the plain-integer legacy signal the RFC names.
	p("printf '%%s' \"$rc\" > /tmp/spawn.exitcode\n")
	p("aws s3 cp /tmp/spawn.exitcode \"$RESULTS_PREFIX/.exitcode\" || true\n\n")

	// ---- signal spored ---- so on_complete fires and `spawn status --check-complete` works.
	p("# ---- signal spored (drives on_complete + spawn status --check-complete) ----\n")
	p("cat > /tmp/SPAWN_COMPLETE <<JSON\n")
	p("{\"status\": \"$STATE\", \"exit_code\": $rc, \"task_id\": %s}\n", jsonStr(taskID))
	p("JSON\n\n")

	p("exit $rc\n")

	return b.String()
}

// quoteArgv single-quotes each argv element and joins with spaces, so the result
// can be placed inside `( … )` and run as a command without a shell re-parse.
func quoteArgv(argv []string) string {
	parts := make([]string, len(argv))
	for i, a := range argv {
		parts[i] = shQuote(a)
	}
	return strings.Join(parts, " ")
}

// writeContainerRun emits the container execution branch: install Docker on
// demand, log in to a private-ECR registry (public images skip login), pull the
// image, and run the argv inside it with the manifest dirs bind-mounted. Stage-in
// already put inputs on the host at those dirs; stage-out reads them back after —
// so the image needs no aws CLI. p writes into the wrapper; each line is indented
// to sit inside the `if [ "$STAGE_RC" -eq 0 ]; then` block.
func writeContainerRun(p func(string, ...interface{}), spec *TaskSpec, region string) {
	image := spec.Container

	// The command script runs as the unprivileged instance user (bootstrap runs it
	// via `su - <user>`), but installing Docker, managing its service, and talking
	// to the Docker socket all need root — so every privileged step here is sudo'd
	// (AL2023's default user has passwordless sudo). The host path never needs this.

	// Install Docker if absent (the task AMI is stock AL2023; no Docker baked in),
	// then make sure the daemon is up before we pull. Failures are fatal to the
	// container run — abort early with a non-zero rc so the completion record
	// classifies it, rather than hanging on a `docker` call to a dead daemon.
	p("  if ! command -v docker >/dev/null 2>&1; then\n")
	p("    echo 'spawn: installing docker...'\n")
	p("    sudo dnf install -y docker\n")
	p("  fi\n")
	p("  sudo systemctl enable --now docker\n")
	// Wait for the socket (service start is async); bounded so we never hang.
	p("  for _i in $(seq 1 30); do sudo docker info >/dev/null 2>&1 && break; sleep 2; done\n")

	// Private-ECR images need a docker login with the instance-role creds; public
	// images pull anonymously. ecrImageAccount!="" ⇒ private ECR ref.
	if ecrImageAccount(image) != "" {
		host := ecrRegistryHost(image)
		p("  echo 'spawn: authenticating to ECR (%s)...'\n", host)
		p("  aws ecr get-login-password --region %s | sudo docker login --username AWS --password-stdin %s\n",
			shQuote(region), shQuote(host))
	}

	// docker run --rm [--gpus all] <-v dir:dir ...> <image> <argv>. --pull always
	// folds the pull into run; rc is the container's exit code. All docker calls
	// are sudo'd (root owns the socket).
	gpuFlag := ""
	if spec.Resources.GPUs > 0 {
		gpuFlag = "--gpus all "
	}
	var mounts strings.Builder
	for _, d := range containerMountDirs(spec) {
		fmt.Fprintf(&mounts, "-v %s:%s ", shQuote(d), shQuote(d))
	}
	p("  sudo docker pull %s\n", shQuote(image))
	p("  sudo docker run --rm %s%s%s %s\n", gpuFlag, mounts.String(), shQuote(image), quoteArgv(spec.Command))
	p("  rc=$?\n")
}

// containerMountDirs returns the distinct host directories to bind-mount into the
// container: the parent dir of each input Destination and each output Source
// (identity-mounted, so in-container paths match the argv the spec author wrote).
// Sorted for a stable wrapper; "/" , "." and empty are skipped.
func containerMountDirs(spec *TaskSpec) []string {
	seen := map[string]bool{}
	var dirs []string
	add := func(p string) {
		d := path.Dir(p)
		if d == "" || d == "." || d == "/" || seen[d] {
			return
		}
		seen[d] = true
		dirs = append(dirs, d)
	}
	for _, m := range spec.Inputs {
		add(m.Destination)
	}
	for _, m := range spec.Outputs {
		add(m.Source)
	}
	sort.Strings(dirs)
	return dirs
}

// recursiveFlag returns " --recursive" when an S3/dir source is a prefix
// (trailing slash), matching `aws s3 cp` semantics for copying a whole prefix.
func recursiveFlag(source string) string {
	if strings.HasSuffix(source, "/") {
		return " --recursive"
	}
	return ""
}

// ecrAccountRe extracts the 12-digit account ID from a private-ECR image host
// (<account>.dkr.ecr.<region>.amazonaws.com/<repo>[:tag]). Mirrors the pure
// helper in cmd/app_byo.go; duplicated here to keep taskproto free of a cmd
// dependency (the JSON contract package must not import the CLI).
var ecrAccountRe = regexp.MustCompile(`^(\d{12})\.dkr\.ecr\.[a-z0-9-]+\.amazonaws\.com/`)

// ecrImageAccount returns the AWS account owning a private-ECR image, or "" if
// the image isn't a private-ECR ref (e.g. a public quay.io/docker.io image).
func ecrImageAccount(image string) string {
	m := ecrAccountRe.FindStringSubmatch(image)
	if m == nil {
		return ""
	}
	return m[1]
}

// ecrRegistryHost returns the registry host (everything before the first '/') —
// the argument `docker login` expects.
func ecrRegistryHost(image string) string {
	if i := strings.IndexByte(image, '/'); i >= 0 {
		return image[:i]
	}
	return image
}

// shQuote wraps s in single quotes, escaping embedded single quotes. This is the
// safe form for shell interpolation (unlike strconv.Quote, which uses
// double-quote semantics and would expand $ and backticks). Copied from the
// pattern in pkg/pluginruntime/remote_executor.go rather than reusing
// security.ShellEscape.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

// jsonStr renders a Go string as a JSON string literal (with surrounding quotes),
// used for the few values interpolated into the heredoc'd completion record.
func jsonStr(s string) string {
	// Escape the characters that matter inside a double-quoted JSON string.
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
