package taskproto

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/spore-host/spawn/pkg/ecrref"
)

// GenerateWrapper builds the self-contained bash script that runs one task on
// its ephemeral instance. It is assigned to aws.LaunchConfig.JobArrayCommand, so
// launcher.Provision embeds it as /etc/spawn/command → /tmp/spawn-command.sh.
// This wrapper IS the reference implementation of the task-execution protocol's
// on-instance contract: stage inputs, run the command, stage outputs, and write
// the durable completion record to S3 — regardless of whether the command
// succeeds.
//
// resultsBucket is the plain bucket name (no s3:// prefix); the record lands
// under tasks/<task_id>/ in it. region is used only for the ECR login of a
// private-registry container image.
//
// Design notes (also commented in the emitted script):
//   - We do NOT `set -e`. Under -e the script would abort the instant the user
//     command exits non-zero, so stage-out and the completion record would never
//     run — defeating the purpose. We capture rc=$? explicitly and gate the rest.
//   - The user command is argv ([]string); each element is single-quoted and run
//     in a subshell (host) or as the container's argv so there is no shell
//     re-parse of a joined string.
//   - Every interpolated value (command args, env values, paths, task_id, image,
//     mount dirs) is single-quoted via shQuote. Env keys are validated in Validate.
//   - When spec.Container is set, the command runs inside that image via `docker
//     run` with the manifest dirs bind-mounted; stage-in/out still happen on the
//     host, so the image needs no aws CLI. Docker is installed on demand.
func GenerateWrapper(spec *TaskSpec, resultsBucket, region string) string {
	return generateWrapper(spec, resultsBucket, region, true)
}

// GeneratePooledJobScript builds the per-job script a POOLED worker runs for one
// task (#70). It is byte-for-byte GenerateWrapper EXCEPT it omits the final
// /tmp/SPAWN_COMPLETE signal: that file drives spored's on_complete action
// (terminate/stop), which is correct for a one-instance-per-task launch but fatal
// for a pooled worker — it would self-terminate after its FIRST task and defeat
// reuse. The worker stays alive and keeps pulling; it drains on idle-timeout
// instead. The durable completion record (completion.json + .exitcode) is still
// written, so the submitter's poll is unchanged.
func GeneratePooledJobScript(spec *TaskSpec, resultsBucket, region string) string {
	return generateWrapper(spec, resultsBucket, region, false)
}

// generateWrapper is the shared body. signalComplete gates the spored
// self-terminate signal: true for the one-instance-per-task wrapper, false for a
// pooled worker's per-job script.
func generateWrapper(spec *TaskSpec, resultsBucket, region string, signalComplete bool) string {
	var b strings.Builder
	p := func(format string, a ...interface{}) { fmt.Fprintf(&b, format, a...) }

	taskID := spec.TaskID
	resultsPrefix := fmt.Sprintf("s3://%s/tasks/%s", resultsBucket, taskID)

	p("#!/bin/bash\n")
	p("# spawn task wrapper — task_id=%s (generated by 'spawn task run', spawn#386)\n", taskID)
	p("# NOTE: intentionally not 'set -e' — we must survive a failing user command\n")
	p("# to still stage outputs and write the durable completion record.\n")
	// `set +e` is explicit, not a no-op default (spawn#566): this text is not
	// always run as its own bash process. pkg/launcher/bootstrap.go writes it
	// (via /etc/spawn/command) verbatim into the TAIL of /tmp/spawn-command.sh,
	// whose own preamble is `#!/bin/bash\nset -e\n...` — the two are concatenated
	// into ONE script file and executed as a single bash invocation, not two. A
	// shell option set early in a script stays in effect for the rest of that
	// same script, so without an explicit `+e` here this text silently inherited
	// `-e` from that preamble despite the comment above: a failing `docker run`
	// (or the host command's subshell) aborted the WHOLE script right there —
	// before `rc=$?` was ever reached — so stage-out, classification, and the
	// completion-record write never ran. That is exactly the field-reported
	// symptom: a failed task with NO completion record at all, riding to TTL
	// instead of self-terminating. Reproduced locally by concatenating this
	// generated script after bootstrap.go's literal `set -e` preamble and running
	// the result with a stand-in `docker` that exits non-zero: completion.json /
	// .exitcode / SPAWN_COMPLETE were never written until this `set +e` was
	// added. Setting it here makes the script correct regardless of whatever
	// shell option state the embedding caller left behind, rather than relying
	// on every embedder to never set -e upstream of it.
	p("set +e -u -o pipefail\n\n")

	p("TASK_ID=%s\n", shQuote(taskID))
	p("RESULTS_PREFIX=%s\n", shQuote(resultsPrefix))
	p("STARTED_AT=\"$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)\"\n")
	// Phase markers. completion.json carries only started_at/ended_at, so the
	// whole interval between them — stage-in, the Docker install, the image pull,
	// the user command, stage-out — is one opaque number. Measured on a real task
	// (cookbook-relion-postprocess-r1): a 94s window of which the user command was
	// 25s, with no way to attribute the other ~69s. These lines make command.log
	// self-timing at the cost of one `date` per phase. Deliberately plain text on
	// stdout rather than a second structured artifact: nothing parses command.log
	// (cmd/service.go's readiness grep is the service path, not this wrapper), and
	// a log a human can read is the thing that was missing.
	p("spawn_phase() { echo \"spawn: [$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)] $*\"; }\n")
	p("spawn_phase 'wrapper start'\n\n")

	// ---- env ----
	if len(spec.Env) > 0 {
		p("# ---- task environment ----\n")
		for _, k := range sortedKeys(spec.Env) {
			p("export %s=%s\n", k, shQuote(spec.Env[k]))
		}
		p("\n")
	}

	// ---- stage-in ----
	p("# ---- stage-in ----\n")
	p("spawn_phase 'stage-in start'\n")
	p("STAGE_RC=0\n")
	// mkdir -p every directory manifestMountDirs will bind-mount (spawn#564):
	// input Destination parents AND output Source parents, from the SAME set
	// `docker run -v` mounts for those manifest entries. Pre-creating them here,
	// as the invoking user, means `docker run` never gets the chance to
	// auto-create a missing bind-mount source itself — which it does as root,
	// mode 0755, leaving the non-root container unable to write into it.
	// Reusing manifestMountDirs' output (rather than recomputing "what needs a
	// mkdir" separately from "what gets mounted") keeps the two lists from
	// drifting apart again.
	//
	// Deliberately NOT containerMountDirs (spawn#570): that function ALSO
	// includes Placement's EFS/FSx/volume mount points, which this loop must
	// NOT mkdir. Those paths are mounted onto by the boot-time storage script
	// (cmd/task.go's taskStorageScript, which runs before this wrapper) —
	// mkdir -p on top of an already-live NFS/Lustre mount is a harmless no-op,
	// but mkdir -p BEFORE that mount lands would create a plain local directory
	// at the mount point, which the later mount then shadows: any file this
	// script writes into it while racing the mount lands on the local disk, not
	// the shared filesystem, and silently disappears from the container's/host's
	// view once the mount completes. Placement mount points must appear in the
	// docker-mount set without ever appearing in this mkdir set.
	for _, dir := range manifestMountDirs(spec) {
		p("mkdir -p %s\n", shQuote(dir))
	}
	p("\n")
	for _, m := range spec.Inputs {
		p("if [ \"$STAGE_RC\" -eq 0 ]; then\n")
		p("  aws s3 cp%s %s %s || STAGE_RC=$?\n", recursiveFlag(m.Source), shQuote(m.Source), shQuote(m.Destination))
		// chown the staged path to the invoking uid:gid right after it lands
		// (spawn#565). Host /tmp is 1777 (sticky): a container that later needs
		// to unlink a staged file may only do so if it OWNS THAT FILE — sharing
		// the directory's uid is not enough under the sticky bit. `aws s3 cp`
		// already runs as the invoking user here, so today this chown is a
		// same-uid no-op in every real call site — it's still emitted
		// unconditionally (not gated on spec.Container) so the invariant
		// "staged files are owned by the uid the container will run as" holds
		// by construction, not by the accident of stage-in and `docker run
		// --user "$(id -u):$(id -g)"` sharing one uninterrupted shell session.
		// Uses the SAME "$(id -u):$(id -g)" that --user passes (#555), so the
		// two can never drift apart. -R for a prefix source (aws s3 cp
		// --recursive populated a whole tree under Destination, not just
		// Destination itself).
		//
		// sudo, not plain chown: a non-root chown can only reassign a file to
		// a uid that ALREADY owns it (verified: `chown` as an unprivileged
		// user to any other uid fails EPERM even for your own file) — so a
		// plain chown here would be a no-op in the case it already matches and
		// silently do nothing in the one case it would need to actually repair
		// a mismatch, defeating the whole point of a defense-in-depth guard.
		// sudo is available: bootstrap.go grants the instance user passwordless
		// sudo, the same precondition writeContainerRun already relies on for
		// every docker/dnf call. Best-effort (|| true): the same-uid case
		// (today, always) can never fail, and if ownership genuinely can't be
		// fixed even as root, the container will surface that itself when it
		// tries to write.
		p("  sudo chown%s \"$(id -u):$(id -g)\" %s 2>/dev/null || true\n", recursiveChownFlag(m.Source), shQuote(m.Destination))
		p("fi\n")
	}
	p("spawn_phase \"stage-in done rc=$STAGE_RC\"\n")
	p("\n")

	// ---- run user command ----
	p("# ---- run user command ----\n")
	p("rc=0\n")
	p("if [ \"$STAGE_RC\" -eq 0 ]; then\n")
	if spec.Container != "" {
		writeContainerRun(p, spec, region)
	} else {
		// Host path: run argv in a subshell (no shell re-parse of a joined string).
		p("  spawn_phase 'command start'\n")
		p("  ( %s )\n", quoteArgv(spec.Command))
		p("  rc=$?\n")
		p("  spawn_phase \"command exit rc=$rc\"\n")
	}
	p("else\n")
	p("  echo 'spawn: stage-in failed; skipping user command' >&2\n")
	p("  rc=$STAGE_RC\n")
	p("fi\n")
	p("ENDED_AT=\"$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)\"\n\n")

	// ---- stage-out (only when the command actually ran; runs even if it failed) ----
	p("# ---- stage-out (runs even when the user command failed) ----\n")
	p("OUT_RC=0\n")
	if len(spec.Outputs) > 0 {
		p("if [ \"$STAGE_RC\" -eq 0 ]; then\n")
		p("  spawn_phase 'stage-out start'\n")
		for _, m := range spec.Outputs {
			p("  aws s3 cp%s %s %s || OUT_RC=$?\n", recursiveFlag(m.Source), shQuote(m.Source), shQuote(m.Destination))
		}
		p("  spawn_phase \"stage-out done rc=$OUT_RC\"\n")
		p("fi\n")
	}
	p("\n")

	// ---- classification + durable completion record ----
	p("# ---- classify + write the durable completion record ----\n")
	// state and retry_class are decided from STAGE_RC / rc / OUT_RC, in that
	// priority order (spawn#561): STAGE_RC means nothing ran at all; rc means the
	// user's command itself failed; only when BOTH of those are clean does OUT_RC
	// get to fail the task — that is the "compute succeeded, delivery failed"
	// case, which is why it gets its own retry class (RetryOutputDeliveryError)
	// rather than reusing RetryStagingError or RetryAppError. Before this, OUT_RC
	// was computed above and never read anywhere: a stage-out failure left
	// STATE=completed/exit_code=0/retry_class="" even though a declared output
	// never reached its destination.
	p("if [ \"$STAGE_RC\" -ne 0 ]; then\n")
	p("  STATE='failed'; RETRY_CLASS='%s'\n", RetryStagingError)
	p("elif [ \"$rc\" -ne 0 ]; then\n")
	p("  STATE='failed'; RETRY_CLASS='%s'\n", RetryAppError)
	p("elif [ \"$OUT_RC\" -ne 0 ]; then\n")
	p("  STATE='failed'; RETRY_CLASS='%s'\n", RetryOutputDeliveryError)
	p("else\n")
	p("  STATE='completed'; RETRY_CLASS=''\n")
	p("fi\n\n")

	// Best-effort copy of the command log; populates logs[] when it succeeds.
	p("LOGS_JSON='[]'\n")
	p("if aws s3 cp /var/log/spawn-command.log \"$RESULTS_PREFIX/command.log\"; then\n")
	p("  LOGS_JSON=\"[\\\"$RESULTS_PREFIX/command.log\\\"]\"\n")
	p("fi\n\n")

	// completion.json — the authoritative record. Built with a heredoc; all
	// interpolated values are either shell ints (rc) or our own controlled strings.
	p("cat > /tmp/spawn-completion.json <<JSON\n")
	p("{\n")
	p("  \"task_id\": %s,\n", jsonStr(taskID))
	p("  \"exit_code\": $rc,\n")
	p("  \"state\": \"$STATE\",\n")
	p("  \"started_at\": \"$STARTED_AT\",\n")
	p("  \"ended_at\": \"$ENDED_AT\",\n")
	p("  \"logs\": $LOGS_JSON,\n")
	p("  \"retry_class\": \"$RETRY_CLASS\"\n")
	p("}\n")
	p("JSON\n")
	p("aws s3 cp /tmp/spawn-completion.json \"$RESULTS_PREFIX/completion.json\" || true\n\n")

	// .exitcode — the plain-integer legacy signal the RFC names.
	p("printf '%%s' \"$rc\" > /tmp/spawn.exitcode\n")
	p("aws s3 cp /tmp/spawn.exitcode \"$RESULTS_PREFIX/.exitcode\" || true\n\n")

	// ---- signal spored ---- so on_complete fires and `spawn status --check-complete` works.
	// A pooled worker (signalComplete=false) SKIPS this: writing SPAWN_COMPLETE would
	// trigger spored's on_complete (terminate/stop) after the FIRST task, killing the
	// worker and defeating reuse. The worker keeps pulling and drains on idle-timeout.
	if signalComplete {
		p("# ---- signal spored (drives on_complete + spawn status --check-complete) ----\n")
		p("cat > /tmp/SPAWN_COMPLETE <<JSON\n")
		p("{\"status\": \"$STATE\", \"exit_code\": $rc, \"task_id\": %s}\n", jsonStr(taskID))
		p("JSON\n\n")
	}

	p("exit $rc\n")

	return b.String()
}

// quoteArgv single-quotes each argv element and joins with spaces, so the result
// can be placed inside `( … )` and run as a command without a shell re-parse.
func quoteArgv(argv []string) string {
	parts := make([]string, len(argv))
	for i, a := range argv {
		parts[i] = shQuote(a)
	}
	return strings.Join(parts, " ")
}

// writeContainerRun emits the container execution branch: install Docker on
// demand, log in to a private-ECR registry (public images skip login), pull the
// image, and run the argv inside it with the manifest dirs bind-mounted. Stage-in
// already put inputs on the host at those dirs; stage-out reads them back after —
// so the image needs no aws CLI. p writes into the wrapper; each line is indented
// to sit inside the `if [ "$STAGE_RC" -eq 0 ]; then` block.
func writeContainerRun(p func(string, ...interface{}), spec *TaskSpec, region string) {
	image := spec.Container

	// The command script runs as the unprivileged instance user (bootstrap runs it
	// via `su - <user>`), but installing Docker, managing its service, and talking
	// to the Docker socket all need root — so every privileged step here is sudo'd
	// (AL2023's default user has passwordless sudo). The host path never needs this.

	// Install Docker if absent (the task AMI is stock AL2023; no Docker baked in),
	// then make sure the daemon is up before we pull. Failures are fatal to the
	// container run — abort early with a non-zero rc so the completion record
	// classifies it, rather than hanging on a `docker` call to a dead daemon.
	p("  spawn_phase 'docker install start'\n")
	p("  if ! command -v docker >/dev/null 2>&1; then\n")
	p("    echo 'spawn: installing docker...'\n")
	p("    sudo dnf install -y docker\n")
	p("  fi\n")
	p("  sudo systemctl enable --now docker\n")
	// Wait for the socket (service start is async); bounded so we never hang.
	p("  for _i in $(seq 1 30); do sudo docker info >/dev/null 2>&1 && break; sleep 2; done\n")
	p("  spawn_phase 'docker install done'\n")

	// Private-ECR images need a docker login with the instance-role creds; public
	// images pull anonymously. ecrImageAccount!="" ⇒ private ECR ref.
	if ecrImageAccount(image) != "" {
		host := ecrRegistryHost(image)
		p("  echo 'spawn: authenticating to ECR (%s)...'\n", host)
		p("  aws ecr get-login-password --region %s | sudo docker login --username AWS --password-stdin %s\n",
			shQuote(region), shQuote(host))
	}

	// docker run --rm --user "$(id -u):$(id -g)" [--gpus all] <-v dir:dir ...>
	// <image> <argv>. rc is the container's exit code. All docker calls are
	// sudo'd (root owns the socket).
	//
	// --user "$(id -u):$(id -g)" (spawn#555): stage-in creates the bind-mounted
	// dirs as the instance user (uid 1000 on AL2023) with the default umask, so
	// they're 0755-owned by that uid. Without --user, the container runs as
	// whatever USER the image declares — and every bioconda/conda-forge image
	// (the entire mambaorg/micromamba-derived ecosystem) declares uid 57439
	// (mambauser), not root and not 1000. On real Linux, bind mounts preserve
	// host uid/gid, so that container gets EACCES writing into its own inputs
	// or outputs. Running the container as the invoking user's uid:gid instead
	// makes the container a packaging detail rather than a different security
	// context — it always matches whoever owns the staged dirs, regardless of
	// the image's declared USER.
	gpuFlag := ""
	if spec.Resources.GPUs > 0 {
		gpuFlag = "--gpus all "
	}
	var mounts strings.Builder
	for _, d := range containerMountDirs(spec) {
		fmt.Fprintf(&mounts, "-v %s:%s ", shQuote(d), shQuote(d))
	}
	p("  spawn_phase 'image pull start'\n")
	p("  sudo docker pull %s\n", shQuote(image))
	p("  spawn_phase 'image pull done; command start'\n")
	p("  sudo docker run --rm --user \"$(id -u):$(id -g)\" %s%s%s %s\n", gpuFlag, mounts.String(), shQuote(image), quoteArgv(spec.Command))
	p("  rc=$?\n")
	p("  spawn_phase \"command exit rc=$rc\"\n")
}

// manifestMountDirs returns the distinct host directories the wrapper's own
// stage-in/stage-out loops populate: the parent dir of each input Destination
// and each output Source (identity-mounted, so in-container paths match the
// argv the spec author wrote). Sorted for a stable wrapper; "/", "." and
// empty are skipped.
//
// The stage-in mkdir loop (above, in generateWrapper) iterates this SAME
// set — deliberately reusing this function's output rather than recomputing
// "what needs a mkdir" independently — so every manifest directory that gets
// bind-mounted also gets pre-created, as the invoking user, before `docker
// run` runs (spawn#564). Previously only input destination parents got an
// explicit `mkdir -p`; an output whose parent wasn't shared with any input
// was left for `docker run -v` to auto-create — which dockerd does as root,
// mode 0755, so the non-root container then got EACCES on its first write.
//
// This function intentionally does NOT include Placement's EFS/FSx/volume
// mount points (spawn#570) — see containerMountDirs below for the superset
// that does, and the comment on the mkdir loop in generateWrapper for why
// mkdir'ing a placement mount point would be actively harmful, not just
// redundant.
func manifestMountDirs(spec *TaskSpec) []string {
	seen := map[string]bool{}
	var dirs []string
	add := func(p string) {
		d := path.Dir(p)
		if d == "" || d == "." || d == "/" || seen[d] {
			return
		}
		seen[d] = true
		dirs = append(dirs, d)
	}
	for _, m := range spec.Inputs {
		add(m.Destination)
	}
	for _, m := range spec.Outputs {
		add(m.Source)
	}
	sort.Strings(dirs)
	return dirs
}

// containerMountDirs returns the distinct host directories to bind-mount into
// the container via `docker run -v`: manifestMountDirs (manifest-derived
// input/output parents) PLUS every Placement mount point the spec's boot-time
// storage script (cmd/task.go's taskStorageScript) already mounted on the
// host — each Placement.Volumes[].MountPath, the EFS mount point (when
// Placement.EFSID is set), and the FSx mount point (when
// Placement.FSxLustreID is set). Sorted for a stable wrapper; "/", "." and
// empty are skipped; duplicates (e.g. a volume mounted under a manifest dir)
// are deduped.
//
// Before spawn#570, writeContainerRun's `docker run -v` list was built from
// manifestMountDirs alone: a container task with an EFS/FSx/volume placement
// but no manifest entry under that path got the filesystem mounted on the
// HOST (taskStorageScript genuinely runs and mounts it) but never bind-mounted
// INTO the container — every containerized task (the aarch.bio/aarch.science
// one-tool-per-image model runs Container != "" for EVERY task) silently lost
// access to placement storage that a host-argv task (Container == "") would
// have seen for free. This function is now the single "what does the
// container get to see" superset; manifestMountDirs stays the narrower "what
// does stage-in need to mkdir" set (see the mkdir loop's comment for why the
// two must NOT be merged back into one list).
func containerMountDirs(spec *TaskSpec) []string {
	dirs := manifestMountDirs(spec)
	seen := map[string]bool{}
	for _, d := range dirs {
		seen[d] = true
	}
	add := func(d string) {
		d = strings.TrimSuffix(d, "/")
		if d == "" || d == "." || d == "/" || seen[d] {
			return
		}
		seen[d] = true
		dirs = append(dirs, d)
	}
	p := spec.Placement
	for _, v := range p.Volumes {
		add(v.MountPath)
	}
	if p.EFSID != "" {
		add(p.EffectiveEFSMountPoint())
	}
	if p.FSxLustreID != "" {
		add(p.EffectiveFSxMountPoint())
	}
	sort.Strings(dirs)
	return dirs
}

// recursiveFlag returns " --recursive" when an S3/dir source is a prefix
// (trailing slash), matching `aws s3 cp` semantics for copying a whole prefix.
func recursiveFlag(source string) string {
	if strings.HasSuffix(source, "/") {
		return " --recursive"
	}
	return ""
}

// recursiveChownFlag returns " -R" for a prefix source (spawn#565): a
// "--recursive" `aws s3 cp` populates a whole tree under Destination, so the
// post-stage chown must walk it too, not just chown the top-level path.
func recursiveChownFlag(source string) string {
	if strings.HasSuffix(source, "/") {
		return " -R"
	}
	return ""
}

// ecrImageAccount returns the AWS account owning a private-ECR image, or "" if
// the image isn't a private-ECR ref (e.g. a public quay.io/docker.io image).
// Thin alias over pkg/ecrref, kept so callers in this file read the same as
// before (was a taskproto-local duplicate of cmd/app_byo.go's helper — now
// shared via the leaf, not copy-pasted a third time).
func ecrImageAccount(image string) string { return ecrref.Account(image) }

// ecrRegistryHost returns the registry host (everything before the first '/') —
// the argument `docker login` expects. Thin alias over pkg/ecrref.
func ecrRegistryHost(image string) string { return ecrref.RegistryHost(image) }

// shQuote wraps s in single quotes, escaping embedded single quotes. This is the
// safe form for shell interpolation (unlike strconv.Quote, which uses
// double-quote semantics and would expand $ and backticks). Copied from the
// pattern in pkg/pluginruntime/remote_executor.go rather than reusing
// security.ShellEscape.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

// jsonStr renders a Go string as a JSON string literal (with surrounding quotes),
// used for the few values interpolated into the heredoc'd completion record.
func jsonStr(s string) string {
	// Escape the characters that matter inside a double-quoted JSON string.
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
